#pragma once
#include <iostream>
#include <fstream>
#include <iterator>
#include <sstream>
#include <string>
#include <vector>
#include "base.h"
#include "chocolate.h"
#include "marshmallow.h"
#include "lollypop.h"
#include "present.h"
#include "sweet.h"
